# Generated by Django 4.2.5 on 2023-10-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_envio',
            field=models.DateTimeField(),
        ),
    ]
